baseurl = "https://shpinkso.github.io/paulblay-hugo/" # Configure URL. if using gh-pages https://github.com/shpinkso/hugo-universal-theme URL: https://shpinkso.github.io/hugo-universal-theme/
title = "Paul Blay"
languageCode = "en-gb"
# theme = "hugo-universal-theme"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# not pluralize title pages by default
pluralizelisttitles = false

[services]
    # Enable comments by entering your Disqus shortname
    [services.disqus]
        shortname = ""
    # Enable Google Analytics by entering your tracking code
    [services.googleAnalytics]
        id = ""

# Define the number of posts per page
[pagination]
    pagerSize = 10

[module]
  [[module.imports]]
    path = "github.com/devcows/hugo-universal-theme"

# Main menu
[menu]
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

# Here's how to add sub menu options:
# basic link
#[[menu.main]]
#    name       = "Option 1: Default Page"
#    url        = "/"
#    weight     = 1
#    parent     = "menu.home"

# Put an image in and create titled columns
#[[menu.main]]
#    name       = "Features"
#    identifier = "menu.features"
#    url        = "/img/template-easy-customize.png"
#    weight     = 3

# Add a column title called "Shortcodes" 
#[[menu.main]]
#    name       = "Shortcodes"
#    identifier = "section.shortcodes"
#    url        = ""
#    weight     = 1
#    parent     = "menu.features"
#    post       = 1

# Add an element under the shortcodes title
#[[menu.main]]
#    name       = "Accordions"
#    url        = ""
#    weight     = 1
#    parent     = "section.shortcodes"


[[menu.main]]
    name       = "About"
    identifier = "menu.about"
    url        = "/about/"
    weight     = 2

[[menu.main]]
    name       = "Blog"
    identifier = "menu.blog"
    url        = "/blog/"
    weight     = 3

[[menu.main]]
    name       = "Resources"
    identifier = "menu.resources"
    url        = "/resources/"
    weight     = 4

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 5


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+12 34 567 89 01"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "https://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "X"
    url = "https://x.com"
    pre = "<i class='fab fa-2x fa-x-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:hello@universal.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devcows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by Devcows using Hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    copyright = "Copyright (c) 2015 - 2025, Paul Blay; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Paul Blay"

    logo = "img/cropped-favicon-1.png"
    logo_small = "img/cropped-favicon-1.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Paul Blay</strong>
        <br>Cambridgeshire
        <br>England
        <br>
        <strong>Great Britain</strong>
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"


[params.home]
    title = "Paul Blay on Software Management"
    subtitle = "Insights into the world of modern software delivery and people management"
    description = "With over 25 years in many different companies, writing software, leading teams and managing projects & programmes – I’ve learned a lot about what works and what definitely does not. This site is intended to share my experience around how to build and maintain great products and services, by guiding and nurturing the teams that create them. My experience is first and foremost in the embedded sector, which brings unique challenges to modern software development practices."
    hero_image = "img/homepage.png"
    hero_image_alt = ""

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = false
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Personal Recommendations"
    subtitle = "Some snippets from the over 20 personal recommendations I've received thoughout my career. See my Linkedin for the full list."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Career Experiences"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Posts from my blog"
    subtitle = ""
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"
