name: Build & Publish (Live)

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to username.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_SECRET }}
          external_repository: Shpinkso/Shpinkso.github.io
          publish_branch: main
          publish_dir: ./public
          cname: paulblay.com
          force_orphan: true
