name: Build & Publish (Preview)

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches-ignore: [ "main" ]   # push to any non-main branch
  workflow_dispatch:

permissions:
  contents: write

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.123.7'
          extended: true

      - name: Compute preview path slug
        id: slug
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "val=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
          else
            echo "val=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Build (Preview)
        run: |
          hugo --minify --environment preview \
               --baseURL "https://shpinkso.github.io/${{ github.event.repository.name }}/previews/${{ steps.slug.outputs.val }}/"

      - name: Publish to gh-pages (keep other previews)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          destination_dir: previews/${{ steps.slug.outputs.val }}
          keep_files: true
          commit_message: "Preview ${{
            github.event.pull_request.number && format('PR #%s', github.event.pull_request.number) || github.ref_name
          }} @ ${{ github.sha }}"
