name: Build & Publish (Preview)

on:
  push:
    branches: ['**']
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.123.7'
          extended: true

      - name: Compute preview path slug
        id: slug
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "val=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
          else
            echo "val=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Build (Preview)
        run: |
          hugo --panicOnWarning --minify --environment preview \
               --baseURL "https://shpinkso.github.io/${{ github.event.repository.name }}/previews/${{ steps.slug.outputs.val }}/"


      - name: Check for broken links and images
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --no-progress
            --base "./public"
            --retry-wait-time 2
            --max-concurrency 20
            --exclude-mail
            --accept 200..299,403
            ./public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to gh-pages (keep other previews)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          destination_dir: previews/${{ steps.slug.outputs.val }}
          keep_files: true
          commit_message: "Preview ${{ steps.slug.outputs.val }} @ ${{ github.sha }}"